### ISSUE TITLE
update suse branding check to look at 'value'

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1352]

**Comment by Josh-Diamond** [comment]
Unable to reproduce or find flaws in logic -- previous failures seen are likely due to a caching issue of some kind.  Closing this out as a non-issue.

More context:
The failure is only seen via Jenkins, and intermittently. When the failure is encountered, ui-brand is being grabbed as `""` when the expected value is `"suse"`.   

When manually checking the Prime env, it is clear that Prime Brand is accurately being displayed and ui-brand is accurately set to `"suse"`, which is expected.
