### ISSUE TITLE
`test_create_ha.py` results in message `[Warning]: error b'Error: Unsupported block type...` when specifying AKS

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#368]
When running the `test_cerate_ha.py` and specifying AKS as the cluster, you will see the following message:

```
[WARNING]: error: b'\nError: Unsupported block type\n\n  on aks.tf line 42, in resource "azurerm_kubernetes_cluster" "default":\n  42:   role_based_access_control {\n\nBlocks of type "role_based_access_control" are not expected here.\n\nError: Unsupported block type\n\n  on aks.tf line 46, in resource "azurerm_kubernetes_cluster" "default":\n  46:   addon_profile {\n\nBlocks of type "addon_profile" are not expected here.\n'
(1, '', '\nError: Unsupported block type\n\n  on aks.tf line 42, in resource "azurerm_kubernetes_cluster" "default":\n  42:   role_based_access_control {\n\nBlocks of type "role_based_access_control" are not expected here.\n\nError: Unsupported block type\n\n  on aks.tf line 46, in resource "azurerm_kubernetes_cluster" "default":\n  46:   addon_profile {\n\nBlocks of type "addon_profile" are not expected here.\n')
```
Consequently, a cluster never gets created as it appears something with regards to the Terraform code is unable to properly handle creating the AKS cluster.

When using the Jenkins job and specifying AKS, a cluster is provisioned as expected. So this appears to be specific to the `test_create_ha.py` script itself, but only for AKS.

**Comment by markusewalker** [comment]
Digging deeper into this, the reason those messages are appearing is because Terraform made the following changes in early March:

- The block `role_based_access_control` has been deprecated in favor of the (optional) property `role_based_access_control_enabled` and block `azure_active_directory_role_based_access_control`.
- `addon_profile.kube_dashboard` is flat out removed since Kube Dashboard is not supported for K8s versions >= 1.19.

Removing both of them obviously fixes the issue, but there are other messages that appear. As this is the case, it seems apparent to me that the AKS terraform files are outdated and need to be overall updated, which will be the focus now.

Reference link: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/website/docs/guides/3.0-upgrade-guide.html.markdown

**Comment by markusewalker** [comment]
Locally, I have a fix for this that appears to be working. My AKS cluster comes up successfully, my K8s resource group in the Azure portal comes up as expected. Additionally, the output that I receive now has equal parity from what we see with our Jenkins job when specifying AKS as the cluster to spin up.

@sowmyav27 I will do more testing next week to ensure consistency, but assuming this fix is fine, I plan to have a PR addressing this next week.

**Comment by markusewalker** [comment]
Installed.
