### ISSUE TITLE
Create/Update internal docs for Windows related info

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#373]
Include this information in the internal confluence page
- [ ] Team responsible
- - [ ] Devs Team
- - [ ] QA team
- [x] How to create new windows AMIs
- [x] What OSes are currently supported

### RKE1
- [ ] Minimum requirements for an RKE1 windows cluster
- [ ] How to Create an RKE1 windows custom cluster
- [ ] Feature charts supported on RKE1
- [ ] How to debug/troubleshoot on a windows RKE1 cluster

### RKE2
- [x] Minimum requirements for an RKE2 windows cluster
- [x] How to Create an RKE2 windows custom cluster
- [x] Minimum requirements for provisioning a vsphere Node driver cluster
- [x] How to Create an RKE2 windows vsphere node driver cluster
- [x] Feature charts supported on RKE2
- [x] How to debug/troubleshoot on a windows RKE2 cluster

### Others:
- [ ] Any existing big issues as of 2.6.5 (latest release)
- [x] Windows Airgap - How to deploy

**Comment by slickwarren** [comment]
for tracking, we also have [this docs issue](https://github.com/rancher/windows/issues/164) that devs will work on (for official documentation) 

rke1 support of windows will be EOL in the upcoming release due to upstream changes. There is still some discussion around this but we have [this ticket tracking the issue](https://github.com/rancher/windows/issues/182). So there might not be much need for internal documentation on rke1 + windows.
