### ISSUE TITLE
Epic - Scale testing 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#41]

**Comment by git-ival** [comment]
Potential Scaling Framework Improvements

1. Re-implement destroy_cluster.sh for clusters module:
    1. Determine which step in the process is actually bottle-necking the destroy (is it removing the clusters from the Rancher host? Is it deleting the instances from aws?)
    2. Add steps that use the aws_cli with necessary access to delete the cluster instances before running through the existing terraform destroy steps for each workspace
2. Improve `terraform destroy` process so that it doesn’t wait until each resource is **actually** fully destroyed before continuing. (Once the resource’s state changes to a “deleting” state then we should trust that the cloud provider will handle the rest)
3. Enable port-forwarding directly to one of the host nodes to access the grafana metrics
    1. The k3s —tls-san flag should allow for this already (need to investigate why this isn’t already allowing for port-forwarding)
4. Create some more robust scripts that provision clusters in reasonable batches > waits for them to provision up to some explicit wait > gathers API and kubectl timings and records them
    1. Could potentially gather information on how many clusters fail to provision properly and gather screenshots of grafana metrics
5. Investigate a way to safely upgrade the cert-manager version used so that it matches the current recommended minimum version in the Rancher docs (should be 1.0.4, is currently at 0.9.1)
    1. This is likely related to some networking requirements/limitations. The current default cert-manager version used does not utilize a webhook, whereas more current releases do not seem to provide a “no webhook" yaml anymore

To Research:

* Maybe replace the framework with IaC/IaS (Infrastructure as Code/Software) tools such as Pulumi or cdk8s?
    * Q: Why? 
    A: Working with Terraform and YAML files directly can become very cumbersome very quickly due to their static nature. Further, these tools allow you to write in actual programming languages (which comes with all the benefits that those languages offer, such as robust error reporting and general familiarity/proficiency).

**Comment by git-ival** [comment]
Each item listed in my previous comment has been completed/actioned in some form. Closing as this issue is no longer useful for our tracking purposes
