### ISSUE TITLE
RKE2 Windows Automation Evaluation and Creation

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/qa-tasks#428]
Acceptance Criteria:

Collaborate with @phillipsj to determine:
- What existing Windows Health Check test(s) already exist
- Determine any gaps in the existing Windows Health Check tests that need to be covered
- Determine if there are any other Windows-related automated tests that need to be created to accomplish automated regression of RKE2 Windows functionality specifically

- Create any tests that I am capable of creating at this time
- Document any tests that need to be created that I am not capable of creating at this time

cc @slickwarren @sowmyav27 @phillipsj 

Tracked in _SURE-5150_

**Comment by jameson-mcghee** [comment]
Information obtained from Jamie Phillips:
As far as Windows Testing goes, I would really focus on getting the automation on par with Linux
•	Add windows images to private registry job
•	Automate provisioning a windows node
From there you could add tests that run Windows workloads in an automated fashion, preferably using Sonobuoy

There are some example workloads here: https://github.com/rancher/windows/tree/main/manifests/workloads

**Comment by slickwarren** [comment]
https://github.com/rancher/rancher/pull/36793/files


Here is our current plan. The above PR has base changes to windows rke2, vsphere, and ec2 + windows. 
* @jameson-mcghee will pull windows rke2 framework functions/files as well as tests related to custom rke2 cluster provisioning
* I will work on the vsphere (+windows rke2) node driver refactor from this PR
* after these are merged, we can salvage the ec2 framework changes as well, however since this is not in scope for 2.7 we can revisit this once we finish the above 2 tasks (note: windows ec2 rke2 node driver is not yet supported in rancher, and is not on the roadmap currently that I'm aware of). 
* Add cluster checks for a windows cluster.
* Add pre upgrade and post upgrade checks for windows clusters
