### ISSUE TITLE
Failing v3_api tests

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#491]
- test_wl_sidekick seemed stuck in an EKS/AKS downstream cluster
- test_wl_with_hostPort is stuck, and needs fixing

**Comment by rishabhmsra** [comment]
While debugging `test_wl_with_hostPort` found that the port it tries to reach is not available in the security group.
- When I tested it on a node driver RKE2 cluster, found that `rancher-nodes` security group is assigned to nodes and it does not have the required ports for this test to get passed, in order to fix it I manually added `open-all` security group to the worker nodes.
- Also cluster should have atleast **two** worker nodes for this test to get pass successfully.

Related issue : https://github.com/rancher/rancher/issues/37460

**Comment by vivek-shilimkar** [comment]
Since, both the host_port issue and sidekick are fixed, closing this issue.
