### ISSUE TITLE
Post Rancher Release checks

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#537]
### Issue Description
As part of post-release checks, we currently manually provision a RKE1/RKE2/K3s cluster. We should automate this into a Jenkins job so that we can save the manual effort during release testing.

- [x] RKE1 - 1 node all roles custom cluster
- [x] RKE2 - 1 node all roles custom cluster
- [x] K3s - 1 node all roles custom cluster

**Comment by slickwarren** [comment]
can we add final RC checks (or would it be worth it to ad those here?):
validate all settings are correctly set to most recent release version:
* /rancherversion: prime = false, version = 2.x.x
* v3/settings/rke-version : <v1.x.x>
* v3/settings/ui-index: ["https://releases.rancher.com/ui/release-<2.x.x>/index.html"](https://releases.rancher.com/ui/release-<2.x.x>/index.html)
* cli-url-linux v3/settings/cli-url-linux : ["https://releases.rancher.com/cli/v1.0.0-alpha8/rancher-linux-amd64-v1.0.0-alpha8.tar.gz"](https://releases.rancher.com/cli/v1.0.0-alpha8/rancher-linux-amd64-v1.0.0-alpha8.tar.gz)
* KDM v3/settings/rke-metadata-config: https://releases.rancher.com/kontainer-driver-metadata/release-v2.7/data.json/
feature-charts [local → apps & market → repositories v2 charts]: release-v2.7
* /v3/setting/kdm-branch: "release-v2.7"
* global →  settings → show rke-metadata-config:  https://releases.rancher.com/kontainer-driver-metadata/release-v2.7/data.json/

**Comment by markusewalker** [comment]
Rancher non-community checks are being handled in separate issue https://github.com/rancher/qa-tasks/issues/544. As such, editing issue to not have those checks.

As we already have existing automation for task 1, we could potentially incorporate a Jenkins job so that during the release testing phase. That way, we can simply run that alongside all the other release / post-release checks.

I'll look into that.

**Comment by markusewalker** [comment]
As discussed in offline meeting, this will be put on the backburner until task https://github.com/rancher/qa-tasks/issues/609 is implemented. Once we have those basic UI checks, the open PR for this task can be revisited and merged.

We are waiting for the aforementioned task because as that will be a Jenkins job ran every post-Rancher release, we want to be sure we incorporate additional manual checks. Not just provisioning clusters.

**Comment by markusewalker** [comment]
Task https://github.com/rancher/qa-tasks/issues/609 has had their PRs merged, so this can be picked back up now. Appropriate PR is currently in review again.

**Comment by markusewalker** [comment]
PR has been merged. Closing issue.
