### ISSUE TITLE
Windows - Automate pushing windows images to registry for Airgap checks

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#551]
Windows - Automate pushing windows images to registry for Airgap checks

Currently we have our tests that pull/push only Linux images to registry. We need a way to automate the windows part.

**Comment by jameson-mcghee** [comment]
The implementation of Airgapped Windows Custom Cluster tests will be accomplished via [478](https://github.com/rancher/qa-tasks/issues/478) (which will likely be broken down into smaller parts, one of which will include the Windows tests) per information from @igomez06. In addition, he stated that @bmdepesa, will likely want this functionality executed via Corral instead of Jenkins, but @igomez06, will confirm this information.

**Comment by bmdepesa** [comment]
```want this functionality executed via Corral instead of Jenkins```

@jameson-mcghee To be clear, Corral is integrated into the test automation framework and is executed from Jenkins like other tests, but yes we should aim for all non-node-driver infrastructure to be created through Corral if possible.

**Comment by slickwarren** [comment]
https://github.com/rancherlabs/corral-packages/pull/13
