### ISSUE TITLE
Refactor Custom Cluster Windows Provisioning Tests

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#618]
As an overview the windows provisioning runs by default when running _TestProvisioningRKE2CustomCluster_ and _TestProvisioningRKE2CustomClusterDynamicInput_ doesn't really run since hasWindows is set to false. Question why isn't isWindows https://github.com/rancher/rancher/blob/530a0c4ed972e607bf4bafc91d273a8ac1c524c2/tests/framework/clients/ec2/config.go#L25 used at all?

Also I think ideally we want a flag coming from the config file where if it is set to false, we can skip the windows tests. That way we can skip them by default.

Here you are going off the assumption that the second config is the windows, what if it's not? 
https://github.com/rancher/rancher/blob/530a0c4ed972e607bf4bafc91d273a8ac1c524c2/tests/framework/extensions/nodes/ec2/ec2.go#L125

**Comment by jameson-mcghee** [comment]
@igomez06, in answer to your first question, I never found a need to utilize it, but it will likely come in handy for the flag you are mentioning, though I am confused why we do not want to run them by default.

In answer to your second question, I initially started to setup the tests so that (for example), another Linux configuration, but for the sake of MVP (and the fact that it will most often/likely be Windows), I kept it simple and just made that assumption, with the thought that we could refactor it to accommodate other OS configurations later (if needed).

**Comment by igomez06** [comment]
Will leave the default behavior and the updates to ec2/nodes will occur with air gap node work.
