### ISSUE TITLE
Validate webhook downstream P0 use cases for downstream cluster level private registry with and without auth enabled

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#651]
**Fresh install:**
**Scenario1**
1. Install rancher 2.7-head
2. Create a downstream cluster with a private registry with auth enabled
3. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
4. Verify the webhook is pulled from the downstream registry.

**Scenario2:**
1. Install rancher 2.7-head
2. Create a downstream cluster with a private registry with NO auth enabled
3. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
4. Verify the webhook is pulled from the downstream registry.

**Comment by vivek-shilimkar** [comment]
Tested the Scenario 1 as follows.

1. Created a rancher v2.7.2-rc6.
2. Created a downstream cluster with a private registry with auth enabled.
3. Verified on the downstream cluster >> Namespace - Cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active.
4. Verified that the webhook is pulled from the downstream registry.
![Screenshot from 2023-03-21 12-09-18](https://user-images.githubusercontent.com/83208989/226534530-18ddb008-f233-421c-8a15-b5100904f3c7.png)

**Comment by vivek-shilimkar** [comment]
Tested the Scenario 1 as follows.

1. Created a rancher v2.7.2-rc6.
2. Created a downstream cluster with a private registry with private registry with NO auth enabled.
3. Verified on the downstream cluster >> Namespace - Cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active.
4. Verified that the webhook is pulled from the downstream registry.
![Screenshot from 2023-03-21 14-24-20](https://user-images.githubusercontent.com/83208989/226558284-eb65b815-c8b3-431a-a2c3-6122c3fcb88f.png)

Since both the scenarios are working closing this issue.
