### ISSUE TITLE
Rhel 9 and Rocky Linux 9 OS support

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#690]
**On 2.6-head Rancher**

|  OS | Private AMI  | Public AMI  | User | 
|---|---|---|---|
| Rhel 9    | ami-02e0cae5bf71fba36 |  ami-067a8829f9ae24c1c | ec2-user |
| Rocky Linux 9  | ami-00b9fa1ea0a07625d | ami-0c30f7eb56d91765c | rocky |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest 1.25 available
- Deploy local clusters using 1.25 k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| Rhel 9 | RKE1 Custom  | PASS | Vivek |
| Rhel 9 | RKE1 Node Driver  | PASS | Vivek |
| Rhel 9  | RKE2 Custom  | PASS | Rishabh |
| Rhel 9  | RKE2 Node Driver  | N/A  |   |
| Rhel 9  | k3s Custom  | PASS | Rishabh |
| Rhel 9  | k3s Node Driver  |   |   |
| Rocky Linux 9 | RKE1 Custom  | PASS | Rishabh |
| Rocky Linux 9 | RKE1 Node Driver | PASS | Rishabh |
| Rocky Linux 9  | RKE2 Custom  | PASS | Rishabh |
| Rocky Linux 9  | RKE2 Node Driver  | N/A  |  - |
| Rocky Linux 9  | K3s Custom  | PASS | Rishabh |
| Rocky Linux 9  | K3s Node Driver  |   |   |

- [x] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| Rhel 9  | RKE1 Imported   | PASS | Vivek |
| Rocky Linux 9  | RKE1 Imported   | PASS| Rishabh |
| Rhel 9  | RKE2 Imported   | PASS |  Max's Team|
| Rocky Linux 9  | RKE2 Imported   | PASS | Max's Team |
| Rhel 9  | k3s Imported   | PASS | Max's Team |
| Rocky Linux 9  | k3s Imported   | PASS | Max's Team |
---
- [x] Chart validations - https://github.com/rancher/qa-tasks/issues/689

**Comment by mitulshah-suse** [comment]
@sowmyav27 testing this on 2.7-head since 1.25 is only available on 2.7. Please advise if otherwise.

**Comment by rishabhmsra** [comment]
On Rocky Linux 9 checks passed, however could not proceed on  RHEL 9 because of below docker issues :
- On previous versions on RHEL, only docker version upto 20.10.7 was supported. Any docker version above that, errors out with `Packages for RHEL are currently only available for s390x`. Please see the details [here](https://github.com/rancher/rancher/issues/34615#issuecomment-1066465005).
- On RHEL 9 docker 20.10.7 is not available and the docker installation script error out with :
```
$ curl https://releases.rancher.com/install-docker/20.10.7.sh | sh
...
Docker CE Stable - x86_64                                                                                                                     59 kB/s |  21 kB     00:00    
Red Hat Enterprise Linux 9 for x86_64 - AppStream from RHUI (RPMs)                                                                            72 kB/s | 4.5 kB     00:00    
Red Hat Enterprise Linux 9 for x86_64 - BaseOS from RHUI (RPMs)                                                                               60 kB/s | 4.1 kB     00:00    
Red Hat Enterprise Linux 9 Client Configuration                                                                                               25 kB/s | 2.0 kB     00:00    
Metadata cache created.
INFO: Searching repository for VERSION '20.10.7'
INFO: yum list --showduplicates 'docker-ce' | grep '20.10.7.*el' | tail -1 | awk '{print $2}'

ERROR: '20.10.7' not found amongst yum list results
```
- Docker 20.10.7 is not present on RHEL 9 and lowest version of docker available on RHEL 9 is `20.10.15:
```
$ yum list --showduplicates 'docker-ce'
...
Available Packages
docker-ce.x86_64                                                              3:20.10.15-3.el9                                                               docker-ce-stable
```
But that error out with `Packages for RHEL are currently only available for s390x`, as versions above 20.10.7 is not supported on RHEL OS.

**Comment by jonathanspw** [comment]
Can you add almalinux alongside this please?

**Comment by mitulshah-suse** [comment]
RHEL9 should be available for testing post this fix
https://github.com/rancher/rancher/issues/41192

**Comment by vivek-shilimkar** [comment]
All the downstream cluster provisioning tests are done and cluster provisioning is working as expected on OS9.

**Comment by vivek-shilimkar** [comment]
OS support testing for RHEL9 and Rocky 9 is finished along with the Chart Validations, hence closing this issue.

**Comment by sowmyav27** [comment]
Reopening for checks on k3s

**Comment by rishabhmsra** [comment]
K3s and RKE2 node driver cluster provisioning using RHEL 9 and Rocky 9 public AMI is failing :

- Provisioned v1.26, ec2 node driver cluster (1-cp, 1-e, 2-w), cluster gets stuck into Updating state with msg : `Configuring bootstrap node(s) rke2-rhel-nd-rishabh-rke2-e-5748798584-696l9: waiting for probes: etcd, kubelet`
- Checked logs on etcd node node and found below error, it might be because of nm-cloud-setup.service enabled on the node.
```
journalctl -u rke2-server.service
...
 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
sh[4081]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
 systemd[1]: rke2-server.service: Control process exited, code=exited, status=1/FAILURE
 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 5.
... 
```
- On further digging found the following documentation about known limitations with RKE2. [#known_issues](https://docs.rke2.io/known_issues/#networkmanager:~:text=In%20some%20operating,should%20be%20disabled)
Also found an issue already logged for RHEL 8.6 [#38216](https://github.com/rancher/rancher/issues/38216)
- As per this [comment](https://github.com/rancher/rancher/issues/37997#issuecomment-1177872112), seems like previously node driver cluster using RHEL was validated using a private ami with all the pre-requisites.
