### ISSUE TITLE
SLE 15 SP5 OS support

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#744]
Additional notes:

- Public Beta — February 21, 2023
- Public RC — April 20, 2023
- First Customer Shipment — End of June 2023

---
**On 2.7-head Rancher**

|  OS | Private AMI  | Public AMI  | User | 
|---|---|---|---|
| SLE 15 SP5    | ami-05b3c1cb5602148d1 `Beta` |   | ec2-user |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest 1.26 available
- Deploy local clusters using 1.26 k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [x] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| SLE 15 SP5 | RKE1 Custom  | PASS | Vivek |
| SLE 15 SP5 | RKE1 Node Driver  | PASS | Vivek |
| SLE 15 SP5  | RKE2 Custom  | PASS | Vivek |
| SLE 15 SP5  | RKE2 Node Driver  | PASS  |  Vivek |
| SLE 15 SP5  | k3s Custom  | PASS | Vivek |
| SLE 15 SP5  | k3s Node Driver  | PASS | Vivek |

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [x] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| SLE 15 SP5| RKE1 Imported   | PASS | Vivek |
| SLE 15 SP5| RKE2 Imported   | PASS | Max's Team |
| SLE 15 SP5| K3s Imported   | PASS | Max's Team |

---
- [x] Chart validations - https://github.com/rancher/qa-tasks/issues/689

**Comment by slickwarren** [comment]
currently ready to test through vsphere

**Comment by vivek-shilimkar** [comment]
### Regarding the SLE 15 SP5 OS Support.

The node driver cluster can't be provisioned on the vSphere because the packages for SLES are only available for s390x.
As of today, there is no Public AMI available for SLE 15 SP5.

Rancher supports SLE 15 SP4 but all the AMIs (Public and Private both) on AWS come with docker pre-installed. Hence, no Public AMIs need the docker installation and user do not encounter the error - `Packages for SLES are currently only available for s390x`.

There are two ways to address the question if SLE 15 SP5 can be added into the Rancher support matrix or not.
1. The OS template on vSphere is in Beta version and if the final version comes with docker already installed on it. Users won't encounter the docker installation error and node driver cluster can be provisioned successfully.
2. The SLE 15 SP5 AMI that I created on AWS can be made Public and be used for provisioning node driver clusters. Since it already has a docker installed user can successfully create a cluster with it. ([Same as SLE 15 SP4](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-0/)).

The following steps were followed to create the SLE 15 SP5 AMI.

1. We already have a SLE 15 SP4 AMIs on AWS us-east-2 region. - I used ami-0fb3a91b7ce257ec1 ~~ami-0094a970bdbeaedcc~~
3. Created an Instance with it.
4. Upgraded the OS from SLE 15 SP4 to SLE 15 SP5 with zypper.
5. Once the upgrade was completed, I created an AMI (ami-05b3c1cb5602148d1) ~~(ami-010268b69524130c4)~~ from the Instance.

As of now this AMI is Private, but if we make it Public SLE 15 SP5 can be added in the Rancher support matrix.

**Comment by vivek-shilimkar** [comment]
Tested the Node Driver cluster creation on Private AMI since Public AMI is not available. 

All the type of cluster creation and chart testing was successful, hence closing this issue.

**Comment by vivek-shilimkar** [comment]
Above testing was done on Beta version of SLE-15-SP5, hence the sanity testing should be done post OS release. 
This ticket - https://github.com/rancher/qa-tasks/issues/776 - will track the sanity testing of SLE-15-SP5.

**Comment by sowmyav27** [comment]
Reopening for k3s checks

**Comment by vivek-shilimkar** [comment]
Tested a custom and node driver k3s along with node driver RKE2 cluster provisioning as mentioned in the ticket. 
All the tests passed. 

Hence closing the issue.
