### ISSUE TITLE
Create SLES AMI from ISO

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#95]
We want to create an AMI to test SLES images that aren't yet available on AWS. 

https://blog.ipswitch.com/import-machine-images-into-aws-with-packer
https://software.opensuse.org/download.html?project=Cloud%3ATools&package=cloud-init

**Comment by rancher-max** [comment]
Blocked by AWS. Steps were:

1. Created a VM in VirtualBox and exported it to OVF. My `sudo` user had password `admin`.

2. Created packer template using that OVF:
```json
{ 
  "variables": {
      "name": "sles15-sp3-betasnapshot16",
      "access_key":"",
      "secret_key":"",
      "region":"us-east-2"
  },
  "builders": [
  {
      "type": "virtualbox-ovf",
      "source_path": "/path/to/sles15sp3.ova",
      "ssh_username": "admin",
      "ssh_password": "admin",
      "ssh_timeout": "6m",
      "format": "ova",
      "shutdown_command": "echo 'admin' | sudo -S shutdown -P now"
  }
  ],
  "post-processors": [
  {
      "type": "amazon-import",
      "access_key": "{{user `access_key`}}",
      "secret_key": "{{user `secret_key`}}",
      "region": "us-east-2",
      "s3_bucket_name": "mytestbucket"
      }
  ]
}
```
3. Ran this with: `packer build -var 'access_key=<mykey>' -var 'secret_key=<mysecret>' ami_sles15sp3_ovf.json`

4. Originally this failed when trying to convert to an ami due to missing a role, which has since been added by EIO: `InvalidParameter: The service role vmimport provided does not exist or does not have sufficient permissions`.

5. Ran manually using aws command line to try to upload after this permission was added. Did this by first creating file:
```json
[
  {
    "Description": "My Server OVA",
    "Format": "ova",
    "UserBucket": {
        "S3Bucket": "mytestbucket",
        "S3Key": "packer-import-1620712992.ova"
    }
}]
```
And then running: `aws ec2 import-image --description "SLES15 SP3 Beta Snapshot16 VMImport" --disk-containers "file:///path/to/thatfile.json"`

**6. Running `aws ec2 describe-import-image-tasks` shows this failed due to AWS not supporting its kernel version yet: `ClientError: Unsupported kernel version 5.3.18-56-default` which we cannot get around at this time.** Further, AWS does not list their supported kernel versions anywhere so it's unclear how to get around this.

**Comment by thehejik** [comment]
I don't know this specific problem but I've uploaded "official" `SLE15-SP3-CHOST-BYOS.x86_64-0.9.8-EC2-GM.raw` image from SUSE - where CHOST means "Container Host" (docker & co. included) and BYOS stands for "Bring your own subscription" (reg. code - which is not needed until you need additional rpm packages).

For this image use private `ami-08a3c932a4b224575I` in `us-east-2` region and `ec2-user` login name for accessing SSH

**Comment by rancher-max** [comment]
I'm going to close this as Tomas uploaded one, and there are now multiple other AMIs for this available both through AWS directly and community.
